const employersFromServer = [
	{
		id: 1,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 2,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 3,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 4,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 5,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 6,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 7,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 8,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 9,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 10,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 11,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 12,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 13,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 14,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 15,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 16,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 17,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 18,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 19,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 20,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 21,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
	{
		id: 22,
		name: 'Justin Septimus',
		company: 'BBS Kraftfahrzeugtechnik',
		email: 'example@mail.com',
		registered: '14.09.2020',
		interviewed: 150,
		hired: 56,
		status: 'active',
	},
];

export default employersFromServer;
